version: 2
jobs:
  build:
    machine:
      java:
        version: oraclejdk8
    steps:
      - checkout
      - run: cat Dockerfile | grep EXPOSE
      - run: mvn test
      - run: mvn package
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
      - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: echo $(git describe --tags)
      - run: echo $CIRCLE_TAG
    # build the application image
      - run: docker build -t garbarinocomar/$CIRCLE_PROJECT_REPONAME:${CIRCLE_BRANCH} .
     # deploy the image
      - run: docker push garbarinocomar/$CIRCLE_PROJECT_REPONAME:${CIRCLE_BRANCH}
      - run: echo "{\"image\":\"garbarinocomar/$CIRCLE_PROJECT_REPONAME:${CIRCLE_BRANCH} \", \"port\":\"5000\", \"env\":[${DEPLOY_ENV_VARS}], \"service_name\":\"${CIRCLE_PROJECT_REPONAME}\"}"
      - run: aws lambda invoke 
            --invocation-type RequestResponse 
            --function-name swarm-ci-deploy 
            --region us-east-1 
            --payload "{\"image\":\"garbarinocomar/$CIRCLE_PROJECT_REPONAME:${CIRCLE_BRANCH} \", \"port\":\"5000\", \"env\":[${DEPLOY_ENV_VARS}], \"service_name\":\"${CIRCLE_PROJECT_REPONAME}\"}" output.txt
      - run: cat output.txt