version: 2
jobs:
 build:
   machine:
     java:
       version: oraclejdk8
   working_directory: ~/circleci-demo-java-spring
   steps:
     - checkout
     - run: mvn test
     - run: mvn package
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
     - run: echo $(git describe --tags)
     - run: echo $CIRCLE_TAG
     # build the application image
     - run: docker build -t gustavoghioldi/$CIRCLE_PROJECT_REPONAME:${CIRCLE_BRANCH} .
     # deploy the image
     - run: docker push gustavoghioldi/$CIRCLE_PROJECT_REPONAME:${CIRCLE_BRANCH}
     - run: aws lambda invoke 
            --invocation-type RequestResponse 
            --function-name swarm-deploy 
            --region us-east-1 
            --payload "{\"branch\":\"$CIRCLE_BRANCH\", \"build\":\"$CIRCLE_BUILD_NUM\", \"key3\":\"value3\"}" output.txt
     - run: cat output.txt