version: 2
jobs:
  build:
    machine:
      java:
        version: oraclejdk8
   
    working_directory: ~/my-project

    steps:
      - checkout
      - run: mvn test
      - run: mvn package
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
      - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: echo $(git describe --tags)
      - run: echo $CIRCLE_TAG
    # build the application image
      - run: docker build -t gustavoghioldi/$CIRCLE_PROJECT_REPONAME:${CIRCLE_BRANCH} .
     # deploy the image
      - run: docker push gustavoghioldi/$CIRCLE_PROJECT_REPONAME:${CIRCLE_BRANCH}
      - run: aws lambda invoke 
            --invocation-type RequestResponse 
            --function-name swarm-deploy 
            --region us-east-1 
            --payload "{\"branch\":\"$CIRCLE_BRANCH\", \"build\":\"$CIRCLE_BUILD_NUM\", \"key3\":\"value3\"}" output.txt
  
  deploy-ci:
    machine: true
    steps:
      - run: echo "hola"
  deploy-prod:
    machine: true
    steps:
      - run: echo "hola"
  
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-ci
        requires:
          - build
        filters:
          branches:
            only: develop
      - deploy-prod
        require:
          - build
        filters:
          branches:
            only: master