Build Timing
version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run:
         name: dockerHub login
         command: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

     # build the application image
     - run: 
         name: build image
         command: docker build -t gustavoghioldi/$CIRCLE_PROJECT_REPONAME:${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM} .
     # deploy the image
     - run: 
         name: push image
         command: docker push gustavoghioldi/$CIRCLE_PROJECT_REPONAME:${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM} 
     - run: 
         name: invoke lambda swarm-deploy
         command: aws lambda invoke 
            --invocation-type RequestResponse 
            --function-name swarm-deploy 
            --region us-east-1 
            --payload "{\"branch\":\"$CIRCLE_BRANCH\", \"build\":\"$CIRCLE_BUILD_NUM\" }" output.txt
     - run: 
         name: view output
         command: cat output.txt