
version: 2
jobs:
 build:
   docker:
     - image: circleci/openjdk:8-jdk
   working_directory: ~/repo
   environment:
   # Customize the JVM maximum heap limit
     MAVEN_OPTS: -Xmx3200m
   
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: mvn integration-test
     - run: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
     - run:
         name: dockerHub login
         command: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

     # build the application image
     - run: 
         name: build image
         command: docker build -t gustavoghioldi/$CIRCLE_PROJECT_REPONAME:${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM} .
     # deploy the image
     - run: 
         name: push image
         command: docker push gustavoghioldi/$CIRCLE_PROJECT_REPONAME:${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM} 
     - run: 
         name: invoke lambda swarm-deploy
         command: aws lambda invoke 
            --invocation-type RequestResponse 
            --function-name swarm-deploy 
            --region us-east-1 
            --payload "{\"branch\":\"$CIRCLE_BRANCH\", \"build\":\"$CIRCLE_BUILD_NUM\" }" output.txt
     - run: 
         name: view output
         command: cat output.txt